name: Automated E2E Testing

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Install dependencies
        run: npm install

      - name: Run Cypress E2E tests
        run: npm run test-e2e-cli
